# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-2deaf6dc-a01a-42f4-84a3-434a11ff1398";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2deaf6dc-a01a-42f4-84a3-434a11ff1398".device = "/dev/disk/by-uuid/2deaf6dc-a01a-42f4-84a3-434a11ff1398";
  boot.initrd.luks.devices."luks-0d7d2a59-8e7b-406d-9444-c7d12de714a6".device = "/dev/disk/by-uuid/0d7d2a59-8e7b-406d-9444-c7d12de714a6";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/81EB-C498";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-0d7d2a59-8e7b-406d-9444-c7d12de714a6"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
